#!/bin/bash
#SBATCH --partition queue0
#SBATCH --nodes 1
#SBATCH --time 00:02:00
#SBATCH --job-name heat_target_map_opt
#SBATCH --output heat_target_map_opt-%j.out

cd $SLURM_SUBMIT_DIR

./heat_target_map_opt
