#!/bin/bash
#SBATCH --partition queue0
#SBATCH --nodes 1
#SBATCH --time 00:02:00
#SBATCH --job-name heat_target_map
#SBATCH --output heat_target_map-%j.out

cd $SLURM_SUBMIT_DIR

./heat_target_map 8000 50
