#!/bin/bash
#SBATCH --partition queue0
#SBATCH --nodes 1
#SBATCH --time 00:02:00
#SBATCH --job-name jac_solv_dat_reg
#SBATCH --output jac_solv_dat_reg-%j.out

cd $SLURM_SUBMIT_DIR

./jac_solv_dat_reg
