#!/bin/bash
#SBATCH --partition queue0
#SBATCH --nodes 1
#SBATCH --time 00:02:00
#SBATCH --job-name vadd_heap_target
#SBATCH --output vadd_heap_target-%j.out

cd $SLURM_SUBMIT_DIR

./vadd_heap_target
